### ISSUE TITLE
Failed to execute golemapp

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/clay#1994]
Reported by @Poppiii on #1815.

I have the same issue but on Windows 10. (golem version 0.11.0)
I checked if geth is running in the background and golem.log is only showing this:

```
2018-01-29 21:30:52 INFO golem.version b'GOLEM Version: 0.11.0 '
2018-01-29 21:30:52 INFO golem.version b'Protocol Version: 20 '
2018-01-29 21:30:52 INFO golem.version b'golem_messages Version: 1.5.1 '
```

**Comment by maaktweluit** [comment]
Hey @Poppiii,

Geth is no longer included in golem on your machine so this error should be from somewhere else.

Strange the log is to small, are these still the only lines in the log file?

If there are no more logs, could you check the following things to zoom in on the problem?
- What is your UAC setting? Some users reported when its OFF the first time you start golem it does not work.
- Is hyperg installed with the right version? The command to test this is `hyperg --version` in cmd.
- Is OpenSSL installed correctly? the command to test this is `where libeay32.dll`

Hope it helps!

Thanks again for the report and helping to make golem better

**Comment by Poppiii** [comment]
Hey,
thank you for your answer.

UAC is on default - Notify me only when programs try to make changes to my computer
hyperg version is 0.2.4
and libeay32.dll is in the Golem folder

**Comment by maaktweluit** [comment]
Based on these checks your setup seems correct.

A few next checks i can think of before asking the team:
- Does "Docker quickstart terminal" open without errors?
- Could you share the log files golem.log and golem.error.log?

**Comment by Poppiii** [comment]
Docker quickstart terminal is opening without errors and version 0.10.0 was working before i updatet to 0.11.0.

Log files:
[golem.log](https://github.com/golemfactory/golem/files/1682775/golem.log)
golem.error.log is empty.

**Comment by maaktweluit** [comment]
Thanks for the logs and the checks.

This all looks correct too, except for the empty log.
Will discuss this with the team and get back to you.

**Comment by maaktweluit** [comment]
Checked in with the team and we came up with 2 possible solutions:
- Could you run golem with debug logs?
  - Close GUI
  - open cmd and run `golemapp --loglevel DEBUG`
  - This should add more lines to the logs
- When debug logs do not give any more info we recommend re-installing the application. Maybe something got corrupted during the upgrade.

**Comment by Poppiii** [comment]
These are the debug logs:
[golem.error.log](https://github.com/golemfactory/golem/files/1687016/golem.error.log)
[golem.log](https://github.com/golemfactory/golem/files/1687017/golem.log)

I hope they help. I already tried to re-install the application.

**Comment by maaktweluit** [comment]
Thank you for the debug logs. They show a bit more but unfortunately not enough.

What we see is it quits while writing to the local database, this could indicate an error in your database.

The database is located at: `%LOCALAPPDATA%\golem\golem\default\golem.db`
Could you zip your database and send it for investigation? To test if a new database helps you can rename the file before starting golem, it will create a new empty one for you.

**Comment by Poppiii** [comment]
I renamed it, but it did not help. Here is the file:
[golem.db.zip](https://github.com/golemfactory/golem/files/1690095/golem.db.zip)

**Comment by mfranciszkiewicz** [comment]
Resolved in https://github.com/golemfactory/golem/pull/2098

**Comment by maaktweluit** [comment]
To resolve this for you before the release we can delete the old task files.
Please make sure golem is NOT running while removing the files.
The problem is in all `*.pickle` files in `C:\Users\<USER>\AppData\Local\golem\golem\default\tasks` and sub-folders.
If you do not care about your task history you can delete the whole `tasks` folder.

**Comment by Poppiii** [comment]
Deleting the task folder did not resolve the problem. I am still getting the same Error.
