### ISSUE TITLE
Setting CPU affinity for Docker containers is broken

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#3037]
Short description of `golem.core.hardware.cpu_cores_available()`:
- reads CPU affinity of Golem's process or the number of system cores as fallback,
- returns a list of available cores, e.g. `[1, 3, 4]`
- `len(cpu_cores_available())` determines the number of cores assigned to the VM (Windows, macOS)
- the returned list is used for specifying cores to be used by Docker containers

`cpu_cores_available()` is broken because:
- _fixed_ ~it no longer works as described in its doc and returns the first (`0`) core~,
- is used both for containers running inside a VM (Windows, macOS) and on the host OS (Linux)
- core numbering inside a VM is not related to Golem's process affinity on host

Issues that follow:
- the first (`0`) core should be skipped on the host OS due to performance reasons
    - Docker VM execution should not be scheduled on the first core (we need to set CPU affinity accordingly) on Windows and macOS
    - Docker containers should not be running on the `0` core on a Linux host
- containers running inside the VM should not fully utilize the `0` core (as seen from inside the VM); a cap is needed for the guest OS to function properly.

Update:
28 V 2019 - "no longer works as described in doc" marked as fixed

**Comment by maaktweluit** [comment]
@mfranciszkiewicz was this solved by the 2 linked PR's?

**Comment by mfranciszkiewicz** [comment]
@maaktweluit The issue is still valid. I've updated the comment with fixes introduced.
