### ISSUE TITLE
it is possible to restart a task with not enough ETH in wallet

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3093]
#### Encountered on:
 Mac OS, Golem version: dev297.g609873b

two subtask of five resubmited from interface in second preview window, during comptations of a subtasks

even though there was not enough ETH for subtask restart. It has been resubmited first, then checked if there is enough ETH for requesting subtask.

Result:
in Gui it looked like subtask has been resubmited but no new node has taken requested subtask
in `golem.log` error appeared:

```
2018-07-25 12:44:44 INFO     golem.task.taskmanager              Task d6fd2b68-8f4b-11e8-aa95-5f40ac920c4a put into restarted state
2018-07-26 12:51:31 INFO     golem.task.taskmanager              Task 497fb8d4-90c0-11e8-8d21-5f40ac920c4a put into restarted state
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 815, in restart_subtasks_from_task
```

```
2018-07-26 12:51:31 ERROR    twisted                             NotEnoughFunds: Not enough ETH available. Required: 0.000560, available: 0.000295: Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 162, in _onMessage
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 895, in onMessage
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 417, in as_future
    
--- <exception caught here> ---
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 815, in restart_subtasks_from_task
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 564, in enqueue_new_task
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/transactions/ethereum/fundslocker.py", line 51, in lock_funds
    
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/transactions/ethereum/ethereumtransactionsystem.py", line 145, in lock_funds_for_payments
    
golem.transactions.ethereum.exceptions.NotEnoughFunds: Not enough ETH available. Required: 0.000560, available: 0.000295
```

Task remained unfinished until timeout.

**Comment by kmazurek** [comment]
Funds validation on task restart endpoints has been added in #4247. This should resolve the issue, assuming that frontend handles the error correctly.

**Comment by ZmijaWA** [comment]
@shadeofblue This is still a problem. We do not have a popup error message with information that something is wrong and the user thinks that he is able to restart task even if he doesn't get enough ETH/GNT. The task will not start and we have the correct info in logs.

**Comment by ederenn** [comment]
gives warning for: restart of single subtask, restart of selected subtasks, restart of timed out subtasks, restart of a whole finished task. 
Restart of a whole task gives warning with different looking modal.
When I'm trying to restart a frame of a finish nothing happens, no restart of a task, no warning.

**Comment by ZmijaWA** [comment]
Still, no warnings when there is not enough GNT or ETH when you try to restart one frame from details view.

**Comment by kmazurek** [comment]
Internally, the RPC used for restarting frames (`comp.task.subtasks.frame.restart`) uses the same method as the one for restarting selected subtasks (`comp.task.subtasks.restart`). Since in the case of restarting selected subtasks the error is correctly reported I believe this is a problem on the frontend side. @mdtanrikulu could you take a look?
While working on this, I think it would make sense to remove the specialised frame restart RPC and move the relevant logic to Electron (as described in [this issue](https://github.com/golemfactory/golem-electron/issues/522)).
