### ISSUE TITLE
problem with too long handshake on many nodes

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4790]
## Description

**Golem Version**: 0.21.0

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used): 0.2.3

**OS** [e.g. Windows 10 Pro]: Linux, Mac

**Branch** (if launched from source): - 

**Mainnet/Testnet**: mainnet 

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

During computations of a tasks repeatedly nodes have problems with handshake. as a result nodes start to ban each other and there is a problem with finishing longer tasks - 40 subtasks and more.

```
ERROR    [golem.resource.client              ] Error executing async, raising. count=1, method=<bound method HyperdriveAsyncClient.get_async of <HyperdriveAsyncClient hyperg at http://localhost:3292>>, args=(), kwargs={'content_hash': '1cd83b66f4efd04b65e89dda3aa2fbfe', 'filename': '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/nonce/tmp', 'filepath': '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/nonce/tmp', 'client_options': <golem.network.hyperdrive.client.HyperdriveClientOptions object at 0x7fc2e01e1fd0>}, exc=JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)
WARNING  [golem.resource.hyperdrive.resourcesmanager] Error downloading resource.path=/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/nonce/tmp/., hash=1cd83b66f4efd04b65e89dda3aa2fbfe, error=[Failure instance: Traceback: <class 'json.decoder.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)
/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py:1464:_inlineCallbacks
--- <exception caught here> ---
/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py:1418:_inlineCallbacks
/home/buildbot-worker/worker/buildpackage_linux/build/golem/network/hyperdrive/client.py:270:_async_request
/usr/lib/python3.6/json/__init__.py:354:loads
/usr/lib/python3.6/json/decoder.py:339:decode
/usr/lib/python3.6/json/decoder.py:357:raw_decode
]
INFO     [golem.resources                    ] Resource handshake error ('d843dfd5..95ee91d6'): <twisted.python.failure.Failure json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)>
INFO     [golem.task.acl                     ] Banned node. node_id=d843dfd5..95ee91d6, timeout=7200s, persist=False
```

**Actual result**:

A lot of subtasks are failing, task might end in timeout. 

![Screenshot from 2019-10-11 18-16-16](https://user-images.githubusercontent.com/32061891/66667649-cef34180-ec53-11e9-9178-b782d64e9125.png)

![Screenshot from 2019-10-11 18-17-12](https://user-images.githubusercontent.com/32061891/66667657-d286c880-ec53-11e9-9e0b-96bb4dab36fa.png)

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch Golem
2. Create a task DiscBoyBlender resolution and samples from file, 30 frames , 60 subtasks, 2.5h for task, 20 min for subtask, bid 0.1.
3. Check logs for error

## Logs and any additional context
Requestor:
[hyperg_2019-10-04_15-24-35.log](https://github.com/golemfactory/golem/files/3718636/hyperg_2019-10-04_15-24-35.log)
[golem (2).log](https://github.com/golemfactory/golem/files/3718641/golem.2.log)
[golem.2019-10-09.log](https://github.com/golemfactory/golem/files/3718646/golem.2019-10-09.log)

Providers:
https://drive.google.com/open?id=1-dLOXErY81SFKUfmIrmyV7eC2PLINw1k
https://drive.google.com/open?id=1gxiPr7vcA-u56kYMi2akvobr7XIrGYEI

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment]
fixed by #4798

**Comment by ederenn** [comment]
After merge of a fix this error still appears quite a lot

```
2019-11-06 12:32:43 WARNING  golem.resource.hyperdrive.resourcesmanager Error downloading resource. res_id=nonce
2019-11-06 12:32:43 INFO     golem.resources                     Resource handshake error ('225c4925..db4531fc'): [Failure instance: Traceback: <class 'json.decoder.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)
/home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
/home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:1464:_inlineCallbacks
--- <exception caught here> ---
/home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:1418:_inlineCallbacks
/home/ederenn/project/golem/golem/network/hyperdrive/client.py:271:_async_request
/usr/lib/python3.6/json/__init__.py:354:loads
/usr/lib/python3.6/json/decoder.py:339:decode
/usr/lib/python3.6/json/decoder.py:357:raw_decode
]
2019-11-06 12:32:43 INFO     golem.task.acl                      Banned node. node_id=225c4925..db4531fc, timeout=7200s, persist=False
```

checked on source, branch b0.21 
`GOLEM Version: 0.21.0+dev25.ge974c2b`
`golem_messages Version: 3.11.0`

**Comment by shadeofblue** [comment]
> After merge of a fix this error still appears quite a lot
> 
> ```
> 2019-11-06 12:32:43 WARNING  golem.resource.hyperdrive.resourcesmanager Error downloading resource. res_id=nonce
> 2019-11-06 12:32:43 INFO     golem.resources                     Resource handshake error ('225c4925..db4531fc'): [Failure instance: Traceback: <class 'json.decoder.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)
> /home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
> /home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
> /home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
> /home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:1464:_inlineCallbacks
> --- <exception caught here> ---
> /home/ederenn/project/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py:1418:_inlineCallbacks
> /home/ederenn/project/golem/golem/network/hyperdrive/client.py:271:_async_request
> /usr/lib/python3.6/json/__init__.py:354:loads
> /usr/lib/python3.6/json/decoder.py:339:decode
> /usr/lib/python3.6/json/decoder.py:357:raw_decode
> ]
> 2019-11-06 12:32:43 INFO     golem.task.acl                      Banned node. node_id=225c4925..db4531fc, timeout=7200s, persist=False
> ```
> 
> checked on source, branch b0.21
> `GOLEM Version: 0.21.0+dev25.ge974c2b`
> `golem_messages Version: 3.11.0`


fixed in: https://github.com/golemfactory/golem/pull/4636
